#!/usr/bin/python

import os
from subprocess import call

ROOT = os.getcwd()

for i in [x for x in os.listdir() if os.path.isdir(x)]:
    print(f'pulling {i} :')
    os.chdir(os.path.join(ROOT, i))
    call(['git', 'pull'])
    print()

