# Plugins
evaluate-commands %sh{
	plugins="$HOME/.config/kak/plugins"
	mkdir -p $plugins
	[ ! -e "$plugins/plug.kak" ] && \
		git clone -q https://github.com/andreyorst/plug.kak "$plugins/plug.kak"
	printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

plug "kak-lsp/kak-lsp" do %{
	cargo install --locked --force --path .
}

plug "lePerdu/kakboard" %{
	hook global WinCreate .* %{ kakboard-enable }
}

plug "enricozb/tabs.kak" %{
	set-option global modelinefmt_tabs '%val{cursor_line}:%val{cursor_char_column} {{context_info}} {{mode_info}}'
	map global normal <tab> ': enter-user-mode tabs<ret>' -docstring 'tabs'
}

# Lsp
set-option global lsp_server_configuration pyls.configurationSources=["flake8"]

# Options
lsp-enable

colorscheme gruvbox

set-option global tabstop 4
set-option global indentwidth 0
set-option global aligntab true
set-option global scrolloff 2,4

add-highlighter global/ number-lines -hlcursor
