#!/sbin/python
import sys
from psutil import *
from subprocess import call, PIPE, Popen

processes = [Process(i) for i in pids()]
process_names = [[i.name()] + i.cmdline() for i in processes]

if sys.argv[1:] in process_names:
    sys.exit(0)
else:
    call(['herbstclient', 'spawn'] + sys.argv[1:])
    sys.exit(0)

